### ISSUE TITLE
/app-design/02-mvc

### ISSUE THREAD

**Issue by colevandersWands** [jankeLearning/content-md#2]

**Comment by colevandersWands** [comment]
hello rien.  if i had any helpful links i could put them here

**Comment by RienCosyns** [comment]
Working on MVC. As exercise I link to tictapps? 
Do we have a project for this? Maybe rebuilding battleship as an MVC app?

**Comment by colevandersWands** [comment]
I looked through and found I have some good amount of old stuff on this.  
I can take this md or pass you the links, your call

**Comment by RienCosyns** [comment]
okay, pass me the links. But this should like to the tictapps exercise, right?

**Comment by colevandersWands** [comment]
The presentation from your program is the best repurposable thing i have around.   
We could look around for links, but mvc's not that complicated.  tictactoes and a good md should be enough

https://docs.google.com/presentation/d/1DRN0fLdsaxKGuPzvVDqx-7r-HuuzJIALNTOGcLsBp6w/edit#slide=id.g1f599b521c_0_26

**Comment by RienCosyns** [comment]
finished for now...
